### ISSUE TITLE
Add back BlogPage modifications

### ISSUE THREAD

**Issue by UltrasonicNXT** [Brickimedia/brickimedia#309]
## TODO
- [ ] Avatar next to "created by" line
- [ ] Prevent secondary title line
- [ ] Default post location to `User_blog:$username/$blogname` (rather than `User_blog:$blogname`)
- [ ] Remove auto-categories

**Comment by neoncitylights** [comment]
_Comment deleted by SamanthaNguyen_

**Comment by georgebarnick** [comment]
No

**Comment by neoncitylights** [comment]
Brickimedia no longer uses GitHub as an issue tracker.
